name: 'sbb'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P9hygyH76PdLPeNRTWCxxygCV4kmuKmy
      MYSQL_DATABASE: sbb
      MYSQL_USER: user
      MYSQL_PASSWORD: NjjQ9eJLqcCWdKDdGUULyZ7Wp6sNqYUd
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: